version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: movie_api_db
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movie_api
      POSTGRES_USER: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
